server:
  port: 9000
  tomcat:
    threads:
      max: ${THREADS_MAX}
      min-spare: ${THREADS_MIN_SPARE}
    max-connections: ${TOMCAT_MAX_CONNECTIONS}
    accept-count: ${TOMCAT_ACCEPT_COUNT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiredTimeMs: ${JWT_EXP_TIME}
